# render.yaml for convenatAI
services:
  - type: web
    name: convenat-ai
    env: docker
    dockerfilePath: ./Dockerfile
    repo: https://github.com/Kodark220/convenatAI
    branch: main
    plan: free
    envVars:
      - key: PORT
        value: "8080"
      - key: GENLAYER_NETWORK
        value: studionet
      - key: GENLAYER_PASSWORD
        value: convenatAI123
      - key: CONVENAT_CONTRACT_ADDRESS
        value: "0xc821A31Bfe1299131D4D07E78a0c7D388B1E9642"
      - key: CIRCLE_API_KEY
        sync: false
      - key: CIRCLE_ENTITY_SECRET
        sync: false
      - key: GENLAYER_PRIVATE_KEY
        sync: false
